apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: votes-submitted
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000